server:
   port: 8888
   context-path: /shopmall
   error:
      whitelabel:
         enabled: false
      
spring:
   application:
       name: shopmall-backend

   profiles:
      active: developer
      
   devtools:
      livereload:
         enabled: true
   
   zipkin:
      baseUrl: http://192.168.1.66:9411/
      
   sleuth:
      enabled: true
      sampler:
         probability: 1
      
   datasource:
      platform: postgres
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.1.66:5432/sm
#      url: jdbc:postgresql://192.168.1.102:5432/smtest
      username: sm
      password: shoppingmall
         
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp  
             
   http:
      encoding:
         charset: UTF-8
         enabled: true
         forced: true
         forced-request: true
         forced-response: true

   
   jpa:
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false
   
mybatis:
   config-location: classpath:mybatis/configuration.xml
   
logging:
   config: classpath:logback.xml

      
      